### ISSUE TITLE
.navigationBar.translucent = YES doesn't display index segments properly

### ISSUE THREAD

**Issue by sedwo** [apolo2/LTPageViewController#2]
Your example code sets `self.navigationController.navigationBar.translucent = NO;`, which seems to have the benefit of adjusting the view to show the horizontal segment index row.  But I'm working with storyboards and they default with translucency = YES, causing the horizontal segment index row to be at the top of the view behind the navigation controller.

**Comment by apolo2** [comment]
Thanks for your comment. I just fixed it
